// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using comply_flow_api.Data;

#nullable disable

namespace comply_flow_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929113402_AddConfigurationPromptVersion")]
    partial class AddConfigurationPromptVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("comply_flow_api.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GenerationMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModelParametersJson")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RuleSetVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TemplateVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("comply_flow_api.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("comply_flow_api.Models.EvaluationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProcessingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingId");

                    b.ToTable("EvaluationResults");
                });

            modelBuilder.Entity("comply_flow_api.Models.MatchedRules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Matched")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("MatchedRules");
                });

            modelBuilder.Entity("comply_flow_api.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("ProcessingId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ProcessingId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("comply_flow_api.Models.PreProcessing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CleanedText")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ProcessingId")
                        .HasColumnType("int");

                    b.Property<string>("StructuredCaseStateJson")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingId")
                        .IsUnique();

                    b.ToTable("PreProcessings");
                });

            modelBuilder.Entity("comply_flow_api.Models.Processing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("int");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("InputMessageId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("InputMessageId");

                    b.ToTable("Processings");
                });

            modelBuilder.Entity("comply_flow_api.Models.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GenerationMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("InputContextJson")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModelParametersJson")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ProcessingId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessingTimeMs")
                        .HasColumnType("int");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TemplateVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingId")
                        .IsUnique();

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("comply_flow_api.Models.ResponsePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProcessingId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RequiredElementsJson")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ResponseStructureJson")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingId")
                        .IsUnique();

                    b.ToTable("ResponsePlans");
                });

            modelBuilder.Entity("comply_flow_api.Models.Rules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProcessingId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RuleSetVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingId")
                        .IsUnique();

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("comply_flow_api.Models.EvaluationResult", b =>
                {
                    b.HasOne("comply_flow_api.Models.Processing", "Processing")
                        .WithMany("EvaluationResults")
                        .HasForeignKey("ProcessingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Processing");
                });

            modelBuilder.Entity("comply_flow_api.Models.MatchedRules", b =>
                {
                    b.HasOne("comply_flow_api.Models.Rules", "Rule")
                        .WithMany("MatchedRules")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("comply_flow_api.Models.Message", b =>
                {
                    b.HasOne("comply_flow_api.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("comply_flow_api.Models.Processing", "Processing")
                        .WithMany("Messages")
                        .HasForeignKey("ProcessingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Processing");
                });

            modelBuilder.Entity("comply_flow_api.Models.PreProcessing", b =>
                {
                    b.HasOne("comply_flow_api.Models.Processing", "Processing")
                        .WithOne("PreProcessing")
                        .HasForeignKey("comply_flow_api.Models.PreProcessing", "ProcessingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Processing");
                });

            modelBuilder.Entity("comply_flow_api.Models.Processing", b =>
                {
                    b.HasOne("comply_flow_api.Models.Configuration", "Configuration")
                        .WithMany("Processings")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("comply_flow_api.Models.Conversation", "Conversation")
                        .WithMany("Processings")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("comply_flow_api.Models.Message", "InputMessage")
                        .WithMany("InputForProcessings")
                        .HasForeignKey("InputMessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Conversation");

                    b.Navigation("InputMessage");
                });

            modelBuilder.Entity("comply_flow_api.Models.Response", b =>
                {
                    b.HasOne("comply_flow_api.Models.Processing", "Processing")
                        .WithOne("Response")
                        .HasForeignKey("comply_flow_api.Models.Response", "ProcessingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Processing");
                });

            modelBuilder.Entity("comply_flow_api.Models.ResponsePlan", b =>
                {
                    b.HasOne("comply_flow_api.Models.Processing", "Processing")
                        .WithOne("ResponsePlan")
                        .HasForeignKey("comply_flow_api.Models.ResponsePlan", "ProcessingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Processing");
                });

            modelBuilder.Entity("comply_flow_api.Models.Rules", b =>
                {
                    b.HasOne("comply_flow_api.Models.Processing", "Processing")
                        .WithOne("Rules")
                        .HasForeignKey("comply_flow_api.Models.Rules", "ProcessingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Processing");
                });

            modelBuilder.Entity("comply_flow_api.Models.Configuration", b =>
                {
                    b.Navigation("Processings");
                });

            modelBuilder.Entity("comply_flow_api.Models.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Processings");
                });

            modelBuilder.Entity("comply_flow_api.Models.Message", b =>
                {
                    b.Navigation("InputForProcessings");
                });

            modelBuilder.Entity("comply_flow_api.Models.Processing", b =>
                {
                    b.Navigation("EvaluationResults");

                    b.Navigation("Messages");

                    b.Navigation("PreProcessing");

                    b.Navigation("Response");

                    b.Navigation("ResponsePlan");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("comply_flow_api.Models.Rules", b =>
                {
                    b.Navigation("MatchedRules");
                });
#pragma warning restore 612, 618
        }
    }
}
